---
# ??? should this be a role in
# https://github.com/nickhardiman/ansible-collection-platform/tree/main/roles

# route traffic to the core network services on another box
# Requires some network shenanigans.
# On a Mac workstation, add routing.
#   sudo route add -net 192.168.135.0/24 192.168.1.135
# On the server, enable forwarding and add routes.

# CLI equivalents of ansible.posix.sysct and rhel-system-roles.network
#   sudo sysctl net.ipv4.ip_forward=1
#   sudo nmcli connection modify bridge-public0 +ipv4.routes "192.168.135.0/24 192.168.1.135"
#   sudo nmcli con up bridge-public0


- name: Configure routing and forwarding for host network
  hosts: hypervisor
  become: true
  gather_facts: true
  roles:

  tasks:

    # https://docs.ansible.com/ansible/latest/collections/ansible/posix/sysctl_module.html
    - name: Set ip forwarding on in /proc and in the sysctl file and reload if necessary
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
        state: present
        reload: true

    - name: Install RPM package
      ansible.builtin.dnf:
        name: rhel-system-roles
        state: present

    # Add a route to the virtual machines on host1
    # by changing the bridge profile.
    # requires gather_facts to set ansible_python
    # not convinced this finishes with re-activation "nmcli con up bridge-public0"
    - name: Use rhel-system-role network
      ansible.builtin.include_role:
        name: rhel-system-roles.network
      vars:
        network_connections:
          - name: "{{ public_nmcli_name }}"
            state: up
            type: bridge
            interface_name: "{{ public_bridge_name }}"
            # interface_name defaults to the connection name
            ip:
              route:
                - network: 192.168.136.0
                  prefix: 24
                  gateway: 192.168.1.195
              dhcp4: true
              auto6: true

    # check
    # ip route list
