---

# network
# MAC addresses are listed here.
#   https://github.com/nickhardiman/ansible-playbook-core/tree/main
#
public_net_short_name: public
public_libvirt_name:   "net{{ public_net_short_name }}0"
public_mac_prefix:     "52:54:00:10"
public_nmcli_name: "bridge-{{ public_net_short_name }}0"
public_bridge_name: "br{{ public_net_short_name }}0"
#
lab_net_short_name: core
lab_libvirt_name:   "net{{ lab_net_short_name }}0"
lab_net_prefix: "192.168.11"
lab_mac_prefix: "52:54:00:11"
lab_domain: "{{ lab_net_short_name }}.example.com"
# DNS Zone names in IPA Server
lab_domain_forward: "{{ lab_domain }}."
lab_domain_reverse: "11.168.192.in-addr.arpa."
